produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }
    
presentation:
    path:     /produits/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }
    
panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }
    
ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouter }
    
supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimer }
    
livraisonadresseSuppression:
    path:     /livraison/adresse/supression/{id}
    defaults: { _controller: EcommerceBundle:Panier:livraisonadresseSuppression }
    
livraison:
    path:     /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }
    
validation:
    path:     /panier/validation
    defaults: { _controller: EcommerceBundle:Panier:validation }
    
#test:
#    path:     /test
#    defaults: { _controller: EcommerceBundle:Test:ajout }

test_form:
    path:     /test_form
    defaults: { _controller: EcommerceBundle:Test:testFormulair }

categorie_produit:
    path:     /categorie/{id}
    defaults: { _controller: EcommerceBundle:Produits:getProduitsByCategorie }

recherche_produit:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Produits:searche }
    
validationCommande:
    path:     /api/banque/{id}
    defaults: { _controller: EcommerceBundle:Commandes:validationCommande }
