parameters:
#  ecommerce.exemple.class: Ecommerce\EcommerceBundle\Example
services:
  setNewReference:
    class: Ecommerce\EcommerceBundle\Service\GetReference
    arguments: [@security.context,@doctrine.orm.entity_manager]

  tva:
    class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
    tags:
      - {name: twig.extension }
  
  redirectionListener:
    class: Ecommerce\EcommerceBundle\Listener\RedirectionListener
    arguments: [@service_container, @session]
    tags:
       - { name: kernel.event_listener, event: kernel.request, method: onkernelRequest}
  
#    ecommerce.example:
#        class: Ecommerce\EcommerceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
